### ISSUE TITLE
Model parameters

### ISSUE THREAD

**Issue by Benzlxs** [zeliu98/CloserLook3D#1]
Hi Ze Liu,

Thanks for your work.
In the paper, table 1 shows that network models with adapt weights and PosPOOL have the same number of parameters, (19.4 M). I am confusing about this, since the model with adapt weights should have more parameters than that with PosPOOL, why are they the same?
Many thanks in advance.

![Screenshot from 2020-07-15 14-08-59](https://user-images.githubusercontent.com/8182276/87502518-15734200-c6a5-11ea-9d6b-62b8748c73a8.png)

Regards,

**Comment by zeliu98** [comment]
Hi Benzlxs, 

Thanks for your interest in our work. In fact they are not the same, for example, the exact parameters for adapt weights is `19397808` while PosPool has `19384416`. The difference is marginal. This is because compared with PosPool, adapt weights only has `3 * in_channel` more parameters, this increase is small in the whole architecture.

Best,
Ze
